#!/usr/bin/env bash

# FIXME cppcheck-2.18 fails to parse: syntaxError, internalAstError.
# Possibly still choking on https://trac.cppcheck.net/ticket/9790
function check_cppcheck_version {
  required_maj=2
  required_min=18

  version=$(cppcheck --version)
  version=${version##Cppcheck }
  version_maj=${version%%.*}
  version=${version#*.}
  version_min=${version%.*}
  # printf "${version_maj}-${version_min}\n"

  if [ "$version_maj" -ne "$required_maj" ]; then
    >&2 printf "\nERROR: Wrong cppcheck major version: $version_maj. Required $required_maj.\n\n"
    exit 1
  fi

  if [ "$version_min" -lt "$required_min" ]; then
    >&2 printf "\nERROR: Wrong cppcheck minor version: $version_min. Required >= $required_min.\n\n"
    exit 1
  fi
}

check_cppcheck_version


cppcheck --std=c23 --language=c \
  --enable=all \
  --safety \
  --inconclusive \
  --template="{file}({line}): {severity} ({id}): {message}" \
  --error-exitcode=1 \
  --inline-suppr \
  --suppress=assertWithSideEffect \
  --suppress=missingIncludeSystem \
  --suppress=ctunullpointer:$MESON_SOURCE_ROOT/tests/utils/bstree.c \
  --suppress=ctunullpointer:$MESON_SOURCE_ROOT/tests/utils/heap.c \
  --suppress=unusedFunction:$MESON_SOURCE_ROOT/src/net/kad/id.h \
  --suppress=unusedFunction:$MESON_SOURCE_ROOT/src/utils/aatree.h \
  --suppress=unusedFunction:$MESON_SOURCE_ROOT/src/utils/byte_array.h \
  --suppress=unusedFunction:$MESON_SOURCE_ROOT/src/utils/list.h \
  -I$MESON_SOURCE_ROOT/src \
  -I$MESON_SOURCE_ROOT/tests \
  -I$MESON_BUILD_ROOT/src \
  -I$MESON_BUILD_ROOT/src/net/kad/.full \
  -I$MESON_BUILD_ROOT/src/net/kad/.tiny \
  $MESON_SOURCE_ROOT/src \
  $MESON_SOURCE_ROOT/tests \
  --check-level=exhaustive \
  --checkers-report=cppcheck-report.txt
  # --xml  # find error id to ignore
  # --check-config
  # --force \
  # -j8  # confuses cppcheck
