#!/usr/bin/env bash
root_dir=$(dirname $0)/..
cd $root_dir
# Make sur to install https://github.com/universal-ctags/ctags, as with etags
# or ordinary ctags, definitions after a macro call WITHOUT a ';' are not
# indexed.
find src tests -type f -name "*.c" -o -name "*.h" | ctags -e -L -
