#! /usr/bin/env python
# Copyright (c) 2014 Foudil Brétel. All rights reserved.

def configure(ctx):
    ctx.env.SRC_DIR = ctx.path.get_src().abspath()
    ctx.load('compiler_c')


def build(ctx):
    # ctx.program(
    #     source   = 'main.c',
    #     target   = ctx.env.APPNAME,
    # )

    if ctx.options.do_valgrind:
        ctx(name = 'valgrind',
            rule   = ('${env.VALGRIND} --leak-check=full --show-leak-kinds=all'
                      ' --error-exitcode=1 ${SRC[0].abspath()}'
                      ' ${ctx.options.do_valgrind}'),
            source = 'termites', # FIXME:
            always = True,
        )
