#! /usr/bin/env python
# Copyright (c) 2014 Foudil Brétel. All rights reserved.

def configure(ctx):
    ctx.env.SRC_DIR = ctx.path.get_src().abspath()
    ctx.load('compiler_c')


def build(ctx):
    # ctx.program(
    #     source   = 'main.c',
    #     target   = ctx.env.APPNAME,
    # )
    pass
